# Supabase CLI configuration

[functions.tg]
verify_jwt = false

[functions.webapp]
verify_jwt = false

[functions.scheduler]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.test-supabase]
verify_jwt = false